---
title: "File Structure"
output: html_document
---

# File Structure

<!--
    Note to self: add intro text
-->

  
## Shared Drive Files

### General Structure

```
Google Drive
  |__ My Drive
  |   |__ Whatever files you have on your GoogleDrive
  |__ Shared drives
      |__ emLab
          |__ Central emLab Resources
          |__ Communications
          |__ Data
          |__ Projects
```

The emLab Shared Drive is organized into four main folders:

* Central emLab Resources: includes meeting and event information, onboarding materials, information about travel reimbursements, and the team roster

* Communications: includes the blog schedule, Adobe design projects, PowerPoint templates, photo repository, and publication and media tracking

* Data: will include the emLab data directory and all datasets we work with

* Projects: includes information on past and current projects, and project management guidelines

A full table of contents can be seen [here](https://docs.google.com/document/d/1a26a6N4akF2dSXWfp0fWxGegd0wvrPVUeaA09en2EPE/edit). 

### Project Folder Structure

```
Google Drive
  |__ Shared drives
      |__ emLab
          |__ Projects
              |__ Archived Projects
              |__ Current Projects
                  |__ Project Example
                      |__ Data
                      |__ Deliverables
                      |__ Grant Reporting
                      |__ Meetings and Events
                      |__ Presentations
                      |__ Project Materials
              |__ Resources
```

Each project folder must contain the following 6 folders:

* Data: all input/raw data will live in the `emLab/Data` folder. This data folder will contain all intermediate datasets as well as output datasets. Be sure to also add a copy of your final datasets to the `emLab/Data` folder and data directory.

* Deliverables: final reports, paper manuscripts, other final deliverables not related to data outputs

* Grant Reporting: grant reports for funders 

* Meetings and Events: meeting notes, agendas, documentation for workshop/event planning

* Presentations: any presentations created for the project

* Project Materials: everything else that does not fit into one of these folders (i.e. drafts of methods, literature review, etc.)

From here, each project can add sub-folders as they see fit within these 6 folders.

### Data Storage

As stated above, there are two folders where data will be stored. The two locations are `emLab/Projects/project_name/Data` and `emLab/Data`. This may seem confusing and redundant, but this section explains the differences between these two locations. As a short summary: `project_name/Data` may contain raw, cleaned, intermediate, and output files for a given project, and will be used as the "workspace" while the project develops. On the other hand, `emLab/Data` contains only input and output data from a finalized project. More detail is provided in the following subsections.

#### `project_name/Data`

**All** data used in a project should live in this project-specific repository. This repository will typically contain at least subfolders for `raw_data` and `data`, although each team might make slight modifications to this structure.

A team will often receive data from partners, compile it from multiple sources, use survey responses, extract it from a literature review, or use results from previous projects as input. These data are termed “raw data”, and should never be directly modified -all the errors, mistakes, and gremlins should be kept in the original versions. Instead, they should be processed / cleaned, and then exported as “clean data”, that can be used in analyses.

For example, suppose that a team working in Montserrat is tasked to perform a stock assessment on lobster populations and receives a database of lobster landings from the government. These data are stored as an excel spreadsheet, and will surely contain many mistakes that need to be fixed prior to running anly analyses. The team will clean the data (preferabily, using a reproducible script), and then export it to a different location within the project folder. The team will then perform the stock assessment, and produce results before reporting back. Therefore, the project-level data folders will be divided into `raw_data` and `data` folders, and perhaps an `output` folder. The first one will contain all raw data as-is. The second folder will contain clean data, whcich can then be used as input for analyses within this project. The `output` folder could contain information relevant to other projects.


```
Projects
|__ ... other projects
|__ montserrat_project
    |__ raw_data
    |   |__ lobster_landings_nov_2012.xslx
    |__ data
        |__ lobster_landings_nov_2012.csv
    |__ output
        |__ lobster_stock_assessment.csv
```

As stated above, the `output` folder could contain information relevant to other projects. Once a project is completed, the raw data and output data should be made available to other emLab projects. To do this, the data should be moved to the `emLab/Data` folder, as described below.

#### `emLab/Data`

As a general rule, this folder will contain all data *used* and *produced* by emLab projects. The idea is to make it esasier for people to find data that is used across projects. At the same time, it makes it easier for future projects to use previous results as input for their work. For example, the [RAM Legacy stock assessment database](https://www.ramlegacy.org/) is key to many projects, and was used as input in the [Costello *et al.* 2016 "upsides" paper](https://www.pnas.org/content/113/18/5125). The "upsides database" is an output from the Costello paper, which can be used as input for other projects. Therefore, the `emLab/Data` folder contains both the RAM and upsides datasets.

This large central data repository has the potential to become messy. Therefore, it is important to follow some key guidelines to store the data. All data in this folder should be a folder that includes at minimum the data and metadata files. For example, a file structure for the two datasets mentioned above might be:

```
emLab
  |__ ...                            [other folders]
  |__ Data
       |__ upsides
       |   |__ _readme_upsides.txt   [the metadata]
       |   |__ upsides.csv           [the data]
       |__ RAM
       |   |__ _readme_RAM.txt       [the metadata]
       |   |__ RAM v4.10             [the data]
       |   |__ RAM v4.15             [the data]
       |   |__ RAM v4.25             [the data]
       |   |__ RAM v4.40             [the data]
       |__ ...                       [other folders]
```

##### Folder Naming

All data folders within the emLab data repository should use a consistent naming style. The naming style for folders is similar to those for data files described above (i.e., be descriptive but concise, avoid spaces, avoid uppercase, avoid special characters), *except* that `-` should be used to separate words. An example folder name could be `blue-paradox-paper` . 

## GitHub Structure
