# Metadata

Metadata is data about your data. It includes information about your data's content, structure, authors, and permissions to make your data interpretable and usable by your future self and others. **Every data file should be accompanied by a metadata file.**

This includes files that people tend to overlook or think are not useful for the broader team. For example, if you're using Google Sheets to keep track of literature or data reviews for a specific project, these documents should also have some form of accompanying metadata.

## Metadata standards

We use "readme" style metadata, named `_readme_datafilename`, and stored in the same folder as the data file.

* Create one readme file for each data file. Download and use this [template](https://drive.google.com/open?id=1AmB69bCh4wqnZFdYuzcXR6R3cKpyUfDT) to create your readme file (when one is not already available).

* Name the readme `_readme_datafilename` and save as a text file.

* Format the readme so it is easy to understand (use bullets, break up information, etc.)

* Use a standardized date format (YYYY-MM-DD)

We acknowledge that it may not always be feasible to draft robust metadata immediately when a dataset is first uploaded to the `emlab/data` folder. In this case, a minimal readme file can be created as a temporary placeholder that contains the following information: your name, contact info, a very brief (1-2 lines) description of the data, and a note on how you obtained them. Please refer to the *Data Directory* subheading for further instruction on how to incorporate this form of temporary documentation into the emLab Data Directory.

For files that may be considered more "internal notes" than datasets (Google Sheets example mentioned above), please ensure that some sort of metadata is present. One alternative to a "readme" file is to create an extra tab on the Google Sheet labeled "metadata". Here, you can include information on the column names (column 1) and their definitions (column 2). This allows collaborators and team members to easily interpret the columns and use the dataset appropriately.

## emLab common data directory {#sec-emlab-data-directory}

All commonly used emLab data is stored in subfolders of the Data folder on the emLab GRIT storage space (`emlab/data`). To document these data, we use the [emLab Data Directory](https://docs.google.com/spreadsheets/d/1lCzpP1X0qPQrqDzVBi78XJQVUumbcQqRck60OkHtANk/edit#gid=0) that includes key, standardized information from each readme metadata file. Every data file in the `emlab/data` folder has a record (row) in the emLab Data Directory. The emLab Data Directory file contains two sheets: (1) Data directory (the record and standardized documentation for each data file); (2) Metadata (information needed to populate the Data Directory, i.e. the meta-metadata)

In the case of placeholder metadata (as described in the *Metadata* section), only the following columns should be filled out: folder, filename, contact, and summary. This (mostly blank) row serves two purposes: 1) it retains some of the searchability function for that dataset and 2) it serves as a visual reminder that those datasets are in need of more robust metadata development.

```r
require(tidyverse)
require(knitr)

meta_metadatatable <- read_csv("images/meta_metadata.csv", col_names = F)
colnames(meta_metadatatable) <- c("Column","Description")
kable(meta_metadatatable)
```

Any time you add a new dataset to the shared emLab data folder and directory, please message the `#data-streamlining` Slack channel so that others on the team know about the new dataset.

## Project-specific data directories {#sec-project-data-directory}

We highly recommend that research teams create a `data_overview` spreadsheet for keeping track of project-related data (i.e. a separate Google Sheet stored in the project's Google Shared Drive folder). This centralized document can be used to document project-relevant information and communicate to team members datasets that have already been saved. This document can then be used to guide and simplify data migration to the [emLab Data Directory](https://docs.google.com/spreadsheets/d/1lCzpP1X0qPQrqDzVBi78XJQVUumbcQqRck60OkHtANk/edit#gid=0) once the project is complete. Suggested attributes include:

  - File name
  - Folder name
  - Source of data
  - Link where data was downloaded
  - Description of data
  - Name of the researcher who downloaded the data
  - Data directory entry (complete, in progress, not started, etc.)
  - Metadata sheet (complete, in progress, not started, etc.)
