# Google Shared Drive {#sec-google-drive}

The Google Shared Drive and GRIT storage space share a very similar
folder structure. The main difference is that the Google Shared Drive
does not have any `data` folders, since all data is stored on GRIT. And
of course, all files on Google Shared Drive are only collaborative
Google Docs/Sheets/Slides. Everything else is stored on GRIT.

## General Structure

```
Google Drive
├── My Drive
│   └── ... whatever files you have on your personal Google Drive ...
└── Shared drives
    └── emLab/
        ├── central-emlab-resources/
        ├── communications/
        └── projects/
```

The emLab Google Shared Drive is organized into three main folders:

-   `central-emlab-resources`: includes meeting and event information,
    project management guidelines, onboarding materials, information
    about travel reimbursements, strategy, computing, and the team
    roster

-   `communications`: includes the blog schedule, publication and media
    tracking, and any Google Docs/Sheets/Slides relating to
    communications

-   `projects`: includes information on past (archive) and current
    projects

The Google Shared Drive and [GRIT](grit-data-storage-space.qmd) storage space share a very similar
folder structure. The main difference is that the Google Shared Drive
does not have any `data` folders, since all data is stored on GRIT.

## Project Folder Structure

```
emLab/projects/
├── archived-projects/
└── current-projects/
    └── ~example-project~/
        ├── deliverables
        ├── grant-eporting
        ├── meetings-and-events
        ├── presentations
        └── project-materials
```

Each project folder must contain at least the following 5 folders:

-   `deliverables`: final reports, paper manuscripts, other final
    deliverables not related to data outputs

-   `grant-reporting`: grant reports for funders

-   `meetings-and-events`: meeting notes, agendas, documentation for
    workshop/event planning

-   `presentations`: any presentations created for the project

-   `project-materials`: everything else that does not fit into one of
    these folders (i.e. drafts of methods, literature review, etc.)

From here, each project can add additional folders or sub-folders as
needed. Just remember that the Google Shared Drive is intended to store only collaborative Google Docs/Sheets/Slides.
